
name: Release Alfred Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: |
          which zip || brew install zip
          pip install xmltodict

      - name: Build and package release
        id: build_release
        run: |
          python3 build_release.py

      - name: Get workflow file name
        id: get_workflow
        run: |
          FILE=$(ls Alfred-Image-Beautifier-*.alfredworkflow 2>/dev/null | head -n 1 || true)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload Asset
        if: steps.get_workflow.outputs.file != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          files: ${{ steps.get_workflow.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and Upload Asset
        if: steps.check.outputs.skip == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.plist_version.outputs.version }}
          files: "Alfred-Image-Beautifier-*.alfredworkflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
