name: Release Alfred Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: |
          which zip || brew install zip

      - name: Generate Alfred Workflow file
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          WORKFLOW_NAME="Alfred-Image-Beautifier-${TAG_NAME}.alfredworkflow"
          zip -r "$WORKFLOW_NAME" . -x '*.git*' '__pycache__/*' '*.pyc' '*.DS_Store'
          echo "Generated $WORKFLOW_NAME"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Alfred-Image-Beautifier-*.alfredworkflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
